const AccountTypes = {
  UPDATE_SIGNUP_FORM: 'UPDATE_SIGNUP_FORM',

  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',

  LOGIN: 'LOGIN',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT: 'LOGOUT',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  RESEND_VERIFICATION: 'RESEND_VERIFICATION',
  RESEND_VERIFICATION_FAILURE: 'RESEND_VERIFICATION_FAILURE',
  RESEND_VERIFICATION_SUCCESS: 'RESEND_VERIFICATION_SUCCESS',
};

export default AccountTypes;
