const CoreTypes = {
  RESET_APP: 'RESET_APP',

  RESET_AUTH_REDIRECT: 'RESET_AUTH_REDIRECT',

  RESET_LAST_PAGE: 'RESET_LAST_PAGE',

  STORE_AUTH_REDIRECT: 'STORE_AUTH_REDIRECT',

  STORE_LAST_PAGE: 'STORE_LAST_PAGE',
};

export default CoreTypes;
