/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "SoleTalkStartCall",
            "endpoint": "https://le9icgfl9j.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:5fe9e1aa-3213-469b-b543-6fe95616a381",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jgBbk9VdJ",
    "aws_user_pools_web_client_id": "ho0qa8oqtcflru5idp83hlqiq",
    "oauth": {}
};


export default awsmobile;
